// GENERATED by scripts/build-extension.ts. Do not edit.
export const DASH_ORIGIN = "https://richardsgeorger-collab.github.io";
export const DASH_URL = "https://richardsgeorger-collab.github.io/school-dashboard/#/now?halo=1";
export const PERIOD_MINUTES = 180;
export const BUILD = "2026-09-24a";
