// GENERATED by scripts/sync-shared.mjs from the src/ copy. Do not edit here.
/**
 * The calendar feed (2026-10-01, Plus): every due date as an .ics a student subscribes to once in Google Calendar,
 * Apple Calendar or Outlook, which then re-reads it on its own schedule. Pure and import-free, so the Edge Function
 * that serves the feed (supabase/functions/calendar) runs this same file (scripts/sync-shared.mjs copies it).
 *
 * Each item is one event at its due time (start = end, the way school calendar feeds show deadlines), titled
 * "ENG-105: Rhetorical analysis draft", with points, the time it takes and a link back to the item in Halo+. Done
 * items stay, marked ✓, so the calendar doesn't look like work vanished. Anything due more than 30 days ago is left
 * out to keep the file small.
 */
export interface FeedItem {
  id: string;
  courseId: string;
  title: string;
  label?: string;
  type?: string;
  points?: number;
  dueAt: string;
  status?: string;
  estimatedMinutes?: number;
}
export interface FeedCourse {
  id: string;
  code: string;
  name?: string;
}

export const FEED_NAME = 'Halo+ deadlines';
const SITE = 'https://haloplus.app/';
const KEEP_PAST_DAYS = 30;

/** RFC 5545 text: backslash, semicolon, comma and newlines escaped. */
export function icsText(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\r?\n/g, '\\n');
}

/** Lines longer than 75 octets are folded (CRLF and one space), never inside a UTF-8 character. */
export function fold(line: string): string {
  const enc = new TextEncoder();
  if (enc.encode(line).length <= 75) return line;
  const out: string[] = [];
  let cur = '';
  let size = 0;
  for (const ch of line) {
    const n = enc.encode(ch).length;
    if (size + n > (out.length ? 74 : 75)) {
      out.push(cur);
      cur = '';
      size = 0;
    }
    cur += ch;
    size += n;
  }
  out.push(cur);
  return out.join('\r\n ');
}

/** 2026-10-01T23:59:00-07:00 → 20261002T065900Z. */
export function icsUtc(iso: string): string {
  return new Date(iso).toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '');
}

const minutes = (m: number) => (m >= 60 ? `${Math.round((m / 60) * 10) / 10}h` : `${m}m`);

export function buildFeed(opts: { items: FeedItem[]; courses: FeedCourse[]; now: string; paused?: boolean }): string {
  const lines = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Halo+//Deadlines//EN', 'CALSCALE:GREGORIAN', 'METHOD:PUBLISH', `X-WR-CALNAME:${FEED_NAME}`, 'X-WR-CALDESC:Your due dates from Halo+. Not affiliated with Grand Canyon University.', 'REFRESH-INTERVAL;VALUE=DURATION:PT1H', 'X-PUBLISHED-TTL:PT1H'];
  const stamp = icsUtc(opts.now);
  if (opts.paused) {
    // The plan no longer includes the feed: one event today that says so, instead of a calendar that silently empties.
    const day = opts.now.slice(0, 10).replace(/-/g, '');
    lines.push('BEGIN:VEVENT', `UID:paused-${day}@haloplus.app`, `DTSTAMP:${stamp}`, `DTSTART;VALUE=DATE:${day}`, 'SUMMARY:Halo+ calendar is paused', `DESCRIPTION:${icsText(`Your plan no longer includes the calendar feed, so your deadlines are not updating here. Open Halo+ to keep it: ${SITE}#/you?s=plan`)}`, `URL:${SITE}#/you?s=plan`, 'END:VEVENT');
  } else {
    const codes = new Map(opts.courses.map((c) => [c.id, c.code]));
    const cutoff = new Date(new Date(opts.now).getTime() - KEEP_PAST_DAYS * 86_400_000).toISOString();
    const items = opts.items.filter((i) => i.dueAt && !Number.isNaN(Date.parse(i.dueAt)) && new Date(i.dueAt).toISOString() >= cutoff).sort((a, b) => Date.parse(a.dueAt) - Date.parse(b.dueAt));
    for (const it of items) {
      const code = codes.get(it.courseId);
      const name = (it.label || it.title || 'Untitled').trim();
      const done = it.status === 'done';
      const summary = `${done ? '✓ ' : ''}${code ? `${code}: ` : ''}${name}`;
      const facts = [it.points ? `${it.points} pts` : null, it.estimatedMinutes ? `about ${minutes(it.estimatedMinutes)}` : null, done ? 'done' : null].filter(Boolean).join(' · ');
      const link = `${SITE}#/class?c=${encodeURIComponent(it.courseId)}&i=${encodeURIComponent(it.id)}`;
      const desc = [it.title && it.title !== name ? it.title : null, facts || null, `Open in Halo+: ${link}`].filter(Boolean).join('\n');
      const at = icsUtc(it.dueAt);
      lines.push('BEGIN:VEVENT', `UID:${it.id}@haloplus.app`, `DTSTAMP:${stamp}`, `DTSTART:${at}`, `DTEND:${at}`, `SUMMARY:${icsText(summary)}`, `DESCRIPTION:${icsText(desc)}`, `URL:${link}`, 'TRANSP:TRANSPARENT', 'END:VEVENT');
    }
  }
  lines.push('END:VCALENDAR');
  return `${lines.map(fold).join('\r\n')}\r\n`;
}
