// GENERATED by scripts/sync-shared.mjs from the src/ copy. Do not edit here.
import { FEATURES, LIMITS, TIERS, TRIAL, type Feature, type Tier } from './tiers.ts';

/**
 * What a user may do, from their tier. The client uses this to show or lock things; the Edge Functions import the
 * same table and refuse what the tier does not allow. The client check is for the experience, the server check is
 * the enforcement.
 */

export const rank = (t: Tier): number => TIERS.indexOf(t);

/** The tier a profile is effectively on right now: a live trial counts as the trial tier. */
export interface TierSource {
  tier: Tier;
  trialEndsAt?: string | null;
  /** Set the moment a trial was started; null means one is still available. */
  trialStartedAt?: string | null;
  /** Set by the Stripe webhook when a payment fails; the paid tier is kept until it passes. */
  graceUntil?: string | null;
  /** A referral reward: this tier until this time, on top of whatever is paid for. */
  rewardTier?: Tier | null;
  rewardUntil?: string | null;
  /** An account that synced Halo on the free plan before 2026-09-28 keeps sync until this date (term end). */
  legacySyncUntil?: string | null;
}

/** The best of what is paid for, a live trial, and a live reward. */
export function effectiveTier(p: TierSource | null | undefined, now = new Date().toISOString()): Tier {
  if (!p) return 'free';
  let best: Tier = p.tier;
  if (p.trialEndsAt && p.trialEndsAt > now && rank(TRIAL.tier) > rank(best)) best = TRIAL.tier;
  if (p.rewardTier && p.rewardUntil && p.rewardUntil > now && rank(p.rewardTier) > rank(best)) best = p.rewardTier;
  return best;
}

/** Days of referral reward left, or null. */
export function rewardDaysLeft(p: TierSource | null | undefined, now = new Date().toISOString()): number | null {
  if (!p?.rewardUntil || p.rewardUntil <= now) return null;
  return Math.ceil((new Date(p.rewardUntil).getTime() - new Date(now).getTime()) / 86_400_000);
}

export const can = (feature: Feature, tier: Tier): boolean => rank(tier) >= rank(FEATURES[feature]);

/** The tier that unlocks a feature, for the upgrade sheet. */
export const tierFor = (feature: Feature): Tier => FEATURES[feature];

/** Days of trial left, or null when there is no live trial. */
export function trialDaysLeft(p: TierSource | null | undefined, now = new Date().toISOString()): number | null {
  if (!p?.trialEndsAt || p.trialEndsAt <= now) return null;
  return Math.ceil((new Date(p.trialEndsAt).getTime() - new Date(now).getTime()) / 86_400_000);
}

/** Where the account stands with the trial. */
export type TrialState = 'available' | 'active' | 'used' | 'paid';
export function trialState(p: TierSource | null | undefined, now = new Date().toISOString()): TrialState {
  if (!p) return 'available';
  if (p.tier === 'max') return 'paid';
  if (p.trialEndsAt && p.trialEndsAt > now) return 'active';
  return p.trialStartedAt ? 'used' : 'available';
}

export interface SyncAccess {
  /** Halo sync may run: Plus or Max, a live trial, or an account kept on it until its term ends. */
  allowed: boolean;
  /** Why it is allowed, or 'none'. */
  via: 'plan' | 'trial' | 'legacy' | 'none';
  /** When it stopped, for "Halo sync paused since Oct 3": the trial's end, or the legacy date. Null if it never ran. */
  pausedSince: string | null;
  /** Set while an account is kept on sync from before the change: the date it ends. */
  legacyUntil: string | null;
}

/**
 * Whether Halo sync may run for this account (2026-09-28: sync is part of Plus). Pure, so every screen asks the same
 * question: the sync sheet, the bookmark's arrival, the frozen banner, the "as of" on due dates.
 */
export function syncAccess(p: TierSource | null | undefined, now = new Date().toISOString()): SyncAccess {
  if (!p) return { allowed: false, via: 'none', pausedSince: null, legacyUntil: null };
  const tier = effectiveTier(p, now);
  const legacy = p.legacySyncUntil && p.legacySyncUntil > now ? p.legacySyncUntil : null;
  if (can('haloManualSync', tier)) return { allowed: true, via: p.trialEndsAt && p.trialEndsAt > now && rank(p.tier) < rank('plus') ? 'trial' : 'plan', pausedSince: null, legacyUntil: legacy };
  if (legacy) return { allowed: true, via: 'legacy', pausedSince: null, legacyUntil: legacy };
  const ended = [p.trialEndsAt, p.legacySyncUntil, p.rewardUntil, p.graceUntil].filter((x): x is string => !!x && x <= now).sort();
  return { allowed: false, via: 'none', pausedSince: ended.length ? ended[ended.length - 1] : null, legacyUntil: null };
}

/** How far ahead Now may suggest work, in days, or null for the whole term. */
export const suggestionWindow = (tier: Tier): number | null => LIMITS.smartSuggestionDays[tier];
