// GENERATED by scripts/sync-shared.mjs from the src/ copy. Do not edit here.
import { FEATURES, LIMITS, TIERS, TRIAL, type Feature, type Tier } from './tiers.ts';

/**
 * What a user may do, from their tier. The client uses this to show or lock things; the Edge Functions import the
 * same table and refuse what the tier does not allow. The client check is for the experience, the server check is
 * the enforcement.
 */

export const rank = (t: Tier): number => TIERS.indexOf(t);

/** The tier a profile is effectively on right now: a live trial counts as the trial tier. */
export interface TierSource {
  tier: Tier;
  trialEndsAt?: string | null;
  /** Set by the Stripe webhook when a payment fails; the paid tier is kept until it passes. */
  graceUntil?: string | null;
}

export function effectiveTier(p: TierSource | null | undefined, now = new Date().toISOString()): Tier {
  if (!p) return 'free';
  if (p.trialEndsAt && p.trialEndsAt > now && rank(TRIAL.tier) > rank(p.tier)) return TRIAL.tier;
  return p.tier;
}

export const can = (feature: Feature, tier: Tier): boolean => rank(tier) >= rank(FEATURES[feature]);

/** The tier that unlocks a feature, for the upgrade sheet. */
export const tierFor = (feature: Feature): Tier => FEATURES[feature];

/** Days of trial left, or null when there is no live trial. */
export function trialDaysLeft(p: TierSource | null | undefined, now = new Date().toISOString()): number | null {
  if (!p?.trialEndsAt || p.trialEndsAt <= now) return null;
  return Math.ceil((new Date(p.trialEndsAt).getTime() - new Date(now).getTime()) / 86_400_000);
}

/** How far ahead Now may suggest work, in days, or null for the whole term. */
export const suggestionWindow = (tier: Tier): number | null => LIMITS.smartSuggestionDays[tier];
