// GENERATED by scripts/sync-shared.mjs from the src/ copy. Do not edit here.
import { AI_CEILING_USD, AI_KIND_FEATURE, AI_WARN_AT, LIMITS, MESSAGE_KINDS, type AiKind, type Tier } from './tiers.ts';
import { can } from './flags.ts';
import { MODEL_PRICES_USD } from './model.ts';

/**
 * Whether one more AI call is allowed, and how close the student is to their limits. Pure: it takes usage rows and
 * a tier and answers. The Edge Function runs the same code on the server's usage log, so the client and the server
 * cannot disagree about what is allowed.
 */

export interface UsageRow {
  /** YYYY-MM-DD in the student's zone. */
  day: string;
  kind: string;
  costUsd: number;
  /** Calls, usually 1 per row. */
  calls?: number;
}

export interface Meter {
  tier: Tier;
  monthCostUsd: number;
  ceilingUsd: number;
  /** 0 to 1, over 1 when the ceiling is passed. */
  ceilingUsed: number;
  messagesToday: number;
  messagesCap: number;
  lecturesThisWeek: number;
  lecturesCap: number;
}

export interface Allowance {
  ok: boolean;
  reason?: 'tier' | 'ceiling' | 'daily' | 'lectures';
  /** Plain words for the screen. */
  message?: string;
  /** True when the student should see a heads-up even though the call is allowed. */
  warn?: boolean;
}

const monthOf = (day: string) => day.slice(0, 7);

/** ISO week start (Monday) of a YYYY-MM-DD, as YYYY-MM-DD. */
function weekStart(day: string): string {
  const d = new Date(`${day}T12:00:00Z`);
  const dow = (d.getUTCDay() + 6) % 7;
  d.setUTCDate(d.getUTCDate() - dow);
  return d.toISOString().slice(0, 10);
}

export function meter(rows: UsageRow[], tier: Tier, today: string): Meter {
  const month = monthOf(today);
  const week = weekStart(today);
  let monthCostUsd = 0;
  let messagesToday = 0;
  let lecturesThisWeek = 0;
  for (const r of rows) {
    if (monthOf(r.day) === month) monthCostUsd += r.costUsd;
    if (r.day === today && (MESSAGE_KINDS as readonly string[]).includes(r.kind)) messagesToday += r.calls ?? 1;
    if (r.kind === 'lecture' && weekStart(r.day) === week) lecturesThisWeek += r.calls ?? 1;
  }
  const ceilingUsd = AI_CEILING_USD[tier];
  return {
    tier,
    monthCostUsd,
    ceilingUsd,
    ceilingUsed: ceilingUsd > 0 ? monthCostUsd / ceilingUsd : monthCostUsd > 0 ? Infinity : 0,
    messagesToday,
    messagesCap: LIMITS.aiMessagesPerDay[tier],
    lecturesThisWeek,
    lecturesCap: LIMITS.lecturesPerWeek[tier],
  };
}

const money = (n: number) => `$${n.toFixed(2)}`;

/** May this kind of call run now? */
export function allowance(kind: AiKind, m: Meter): Allowance {
  const feature = AI_KIND_FEATURE[kind];
  if (!can(feature, m.tier)) return { ok: false, reason: 'tier', message: `This needs a higher plan.` };
  if (m.ceilingUsd <= 0 || m.monthCostUsd >= m.ceilingUsd) {
    return { ok: false, reason: 'ceiling', message: `AI is paused until the 1st: this month's AI budget (${money(m.ceilingUsd)}) is used up. Everything else keeps working.` };
  }
  if ((MESSAGE_KINDS as readonly string[]).includes(kind) && m.messagesToday >= m.messagesCap) {
    return { ok: false, reason: 'daily', message: `That is ${m.messagesCap} messages for today. More tomorrow.` };
  }
  if (kind === 'lecture' && m.lecturesThisWeek >= m.lecturesCap) {
    return { ok: false, reason: 'lectures', message: `That is ${m.lecturesCap} lectures this week. More next week.` };
  }
  return { ok: true, warn: m.ceilingUsed >= AI_WARN_AT };
}

/** The heads-up line at 80%, or null. */
export function warningLine(m: Meter): string | null {
  if (m.ceilingUsd <= 0 || m.ceilingUsed < AI_WARN_AT || m.ceilingUsed >= 1) return null;
  return `You have used ${Math.round(m.ceilingUsed * 100)}% of this month's AI. It pauses at 100% and comes back on the 1st.`;
}

/** Dollars for one call, from the usage the API reported. */
export function costOf(usage: { input_tokens?: number; output_tokens?: number; cache_read_input_tokens?: number; cache_creation_input_tokens?: number }): number {
  const p = MODEL_PRICES_USD;
  return ((usage.input_tokens ?? 0) * p.input + (usage.output_tokens ?? 0) * p.output + (usage.cache_read_input_tokens ?? 0) * p.cacheRead + (usage.cache_creation_input_tokens ?? 0) * p.cacheWrite) / 1_000_000;
}
