// GENERATED by scripts/sync-shared.mjs from the src/ copy. Do not edit here.
import { GRACE_DAYS, STRIPE_PRICE_IDS, type Tier } from './tiers.ts';

/**
 * What a Stripe subscription means for a profile. Pure, shared with the webhook, so the client and the server
 * agree on what "past due" and "canceled" do to a plan. Stripe's statuses: trialing, active, past_due, unpaid,
 * canceled, incomplete, incomplete_expired, paused.
 */
export interface SubscriptionFacts {
  status: string;
  priceId: string | null;
  currentPeriodEnd: string | null;
  cancelAtPeriodEnd: boolean;
}

export type Paid = Exclude<Tier, 'free'>;
export type Interval = 'month' | 'year';

/** The plan a Stripe price id stands for, or null for a price this build does not know. */
export function tierForPrice(priceId: string | null): { tier: Paid; interval: Interval } | null {
  if (!priceId) return null;
  for (const tier of Object.keys(STRIPE_PRICE_IDS) as Paid[]) {
    for (const interval of ['month', 'year'] as Interval[]) {
      if (STRIPE_PRICE_IDS[tier][interval] === priceId) return { tier, interval };
    }
  }
  return null;
}

const addDays = (iso: string, days: number) => new Date(new Date(iso).getTime() + days * 86_400_000).toISOString();

/**
 * The profile columns a subscription sets. Active or trialing keeps the paid tier. Past due keeps it too, for the
 * grace period, so a card that expired on the 1st does not lock a student out mid-week. Everything else is Free.
 */
export function profilePatch(facts: SubscriptionFacts, now: string): { tier: Tier; grace_until: string | null } {
  const known = tierForPrice(facts.priceId);
  const tier: Tier = known?.tier ?? 'free';
  switch (facts.status) {
    case 'active':
    case 'trialing':
      return { tier, grace_until: null };
    case 'past_due':
      return { tier, grace_until: addDays(now, GRACE_DAYS) };
    default:
      return { tier: 'free', grace_until: null };
  }
}

/** The row for the subscriptions table, or null when the price is not one of ours. */
export function subscriptionRow(facts: SubscriptionFacts, userId: string, subscriptionId: string, now: string) {
  const known = tierForPrice(facts.priceId);
  if (!known) return null;
  return {
    user_id: userId,
    stripe_subscription_id: subscriptionId,
    tier: known.tier,
    interval: known.interval,
    status: facts.status,
    current_period_end: facts.currentPeriodEnd,
    cancel_at_period_end: facts.cancelAtPeriodEnd,
    updated_at: now,
  };
}

/** One line for the account card. */
export function subscriptionLine(row: { tier: Paid; interval: Interval; status: string; current_period_end: string | null; cancel_at_period_end: boolean } | null, graceUntil: string | null, fmtDay: (iso: string) => string): string | null {
  if (graceUntil && new Date(graceUntil).getTime() > Date.now()) return `Payment failed. Update your card by ${fmtDay(graceUntil)} to keep your plan.`;
  if (!row) return null;
  const when = row.current_period_end ? fmtDay(row.current_period_end) : null;
  if (row.status === 'canceled') return 'Your plan has ended.';
  if (row.cancel_at_period_end && when) return `Ends ${when}. Nothing more will be charged.`;
  if (when) return `Renews ${when}, ${row.interval === 'year' ? 'yearly' : 'monthly'}.`;
  return null;
}
