// Builds the Chrome extension's generated files from the same bookmarklet source the app ships, in 'message'
// delivery mode. Run with `npm run build:extension`. The rest of extension/ is hand-written.
import { mkdirSync, writeFileSync } from 'node:fs';
import { BOOKMARKLET_BUILD, bookmarkletSource } from '../src/halo/bookmarklet';

const origin = process.env.EXT_DASH_ORIGIN ?? 'https://haloplus.app';
const path = process.env.EXT_DASH_PATH ?? '/#/now?halo=1';
// Where every sync goes first: the account's pending slot on the server, so it lands with no Halo+ tab open.
const supabaseUrl = (process.env.EXT_SUPABASE_URL ?? process.env.VITE_SUPABASE_URL ?? 'https://kiacmspgvntzwngijibr.supabase.co').replace(/\/$/, '');
mkdirSync('extension', { recursive: true });
writeFileSync('extension/sync-inject.js', `// GENERATED by scripts/build-extension.ts from src/halo/bookmarklet.ts (build ${BOOKMARKLET_BUILD}). Do not edit.\n${bookmarkletSource({ dashOrigin: origin, dashPath: path, deliver: 'message' })}\n`);
writeFileSync('extension/config.js', `// GENERATED by scripts/build-extension.ts. Do not edit.\nexport const DASH_ORIGIN = ${JSON.stringify(origin)};\nexport const DASH_URL = ${JSON.stringify(origin + path)};\nexport const PERIOD_MINUTES = 180;\nexport const DROP_URL = ${JSON.stringify(supabaseUrl + '/functions/v1/sync-drop')};\nexport const REPORT_URL = ${JSON.stringify(supabaseUrl + '/functions/v1/report')};\nexport const BUILD = ${JSON.stringify(BOOKMARKLET_BUILD)};\n`);
console.log(`extension built for ${origin} (bookmarklet ${BOOKMARKLET_BUILD})`);
