// Check Halo: first press copies the prompt and opens Halo with a hint; second press opens the paste box; results flow into the review.
import puppeteer from 'puppeteer-core';
const BASE = process.env.BASE ?? 'http://localhost:4173/school-dashboard/';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const ctx = browser.defaultBrowserContext();
await ctx.overridePermissions(new URL(BASE).origin, ['clipboard-read', 'clipboard-write', 'clipboard-sanitized-write']);
const page = await browser.newPage();
await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
page.on('pageerror', (e) => console.log('PAGE ERROR:', e.message));
const t = (sel) => page.$eval(sel, (el) => el.textContent.replace(/\s+/g, ' ').trim()).catch(() => null);
const opened = [];
browser.on('targetcreated', (tg) => opened.push(tg.url()));
await page.goto(`${BASE}#/now`, { waitUntil: 'networkidle0' });
await page.click('button[aria-label="Check Halo"]');
await sleep(800);
console.log('hint:', await t('.halo-banner'));
console.log('opened tab:', opened.find((u) => u.includes('halo.gcu.edu')) ?? opened.join(','));
for (const tg of browser.targets()) if (tg.url().includes('halo.gcu.edu')) { const p = await tg.page(); if (p) await p.close(); }
await page.bringToFront();
await sleep(300);
const clip = await page.evaluate(() => navigator.clipboard.readText());
console.log('clipboard starts:', JSON.stringify(clip.slice(0, 60)), '| has planner list:', /MY PLANNER/.test(clip), '| lines:', clip.split('\n').length, '| sample line:', clip.split('\n').find((l) => /^CHM-113 \|/.test(l)));
console.log('modal opened on first press:', !!(await page.$('.modal')));
// Second press: paste box.
await page.click('button[aria-label="Check Halo"]');
await page.waitForSelector('.modal textarea', { timeout: 5000 });
const quiz = await page.evaluate(() => { const s = JSON.parse(localStorage.getItem('school-dashboard:v1')); const chm = s.courses.find((c) => c.code === 'CHM-113'); return s.items.filter((i) => i.courseId === chm.id && i.type === 'quiz' && i.status !== 'done').sort((a, b) => a.dueAt.localeCompare(b.dueAt))[0]; });
const results = [`CHM-113 | ${quiz.title} | changed | 2026-10-02 23:59 | was ${quiz.dueAt.slice(0, 10)}`, 'ESG-162 | Section 2.4 Worksheet | new | 2026-09-30 08:00 | 15 pts', 'ENG-105 | Peer Review 1 | missing | | not in Halo', 'UNV-106 | Topic 3 DQ 1 | same', 'this line means nothing'].join('\n');
await page.$eval('.modal textarea', (el, v) => { const set = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set; set.call(el, v); el.dispatchEvent(new Event('input', { bubbles: true })); }, results);
await sleep(200);
console.log('read line:', await t('.modal .hint.mono'));
await page.$$eval('.modal .btn.primary', (els) => els[0].click());
await page.waitForSelector('.rev-mention', { timeout: 5000 });
console.log('review rows:', await page.$$eval('.rev-mention', (els) => els.map((e) => `${e.querySelector('.rev-badge').textContent} ${e.querySelector('.chip')?.textContent.trim() ?? '?'}: ${e.querySelector('.rev-proposal').textContent.replace(/\s+/g, ' ').trim()}`).join(' || ')));
await page.screenshot({ path: process.argv[2] ?? 'check.png', fullPage: false });
await page.$$eval('.rev-mention:first-child .rev-actions .btn', (els) => els[0].click());
await sleep(300);
const after = await page.evaluate((id) => JSON.parse(localStorage.getItem('school-dashboard:v1')).items.find((i) => i.id === id).dueAt, quiz.id);
console.log('after approve:', quiz.title, quiz.dueAt, '→', after);
await page.$$eval('.modal .modal-actions .btn.primary', (els) => els[0].click());
await sleep(200);
console.log('pending cleared:', await page.evaluate(() => localStorage.getItem('school-dashboard:halo-check')) === null);
// Settings: the prompt is editable and persists.
await page.goto(`${BASE}#/settings`, { waitUntil: 'networkidle0' });
await page.$eval('textarea[aria-label="Check Halo prompt"]', (el) => { const set = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set; set.call(el, 'My own audit words'); el.dispatchEvent(new Event('input', { bubbles: true })); });
await sleep(200);
console.log('prompt saved:', await page.evaluate(() => JSON.parse(localStorage.getItem('school-dashboard:v1')).settings.haloAuditPrompt));
await page.$$eval('.settings-card .btn', (els) => els.find((e) => e.textContent.trim() === 'Copy full prompt').click());
await sleep(200);
console.log('copied custom:', (await page.evaluate(() => navigator.clipboard.readText())).startsWith('My own audit words\n\nMY PLANNER'));
await browser.close();
