// The Edge Functions run the same tier, flag, meter and model code as the client. Deno cannot import from src/, so
// this copies the four files into supabase/functions/_shared/ with Deno-style imports. `src/config/shared.test.ts`
// fails when the copies are out of date, so a changed limit cannot ship to the client alone.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dirname, '..');
const out = join(root, 'supabase', 'functions', '_shared');
mkdirSync(out, { recursive: true });

export const SHARED = [
  ['src/config/tiers.ts', 'tiers.ts'],
  ['src/config/flags.ts', 'flags.ts'],
  ['src/ai/model.ts', 'model.ts'],
  ['src/ai/meter.ts', 'meter.ts'],
];

/** Deno wants explicit extensions on relative imports; the sources all sit in one flat folder there. */
export function toDeno(source) {
  return `// GENERATED by scripts/sync-shared.mjs from the src/ copy. Do not edit here.\n${source
    .replace(/from '\.\.\/config\/(\w+)'/g, "from './$1.ts'")
    .replace(/from '\.\/(\w+)'/g, "from './$1.ts'")}`;
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  for (const [from, to] of SHARED) writeFileSync(join(out, to), toDeno(readFileSync(join(root, from), 'utf8')));
  console.log(`synced ${SHARED.length} shared files to supabase/functions/_shared/`);
}
